#!/bin/bash
# 

add_host(){

	# Validate if exist address node.
	if [ $(avahi-resolve-address -n ${NODENAME}.${CLOUD_NAME}.local 2> /dev/null | grep "${PUBLIC_IP}" | wc -l) -lt 1 ]
	then 
		avahi-publish-address -R ${NODENAME}.${CLOUD_NAME}.local ${PUBLIC_IP} &
	fi

}

rem_host(){
	
		local _PROCES

		_PROCES=$(avahi-publish-address -R ${NODENAME}.${CLOUD_NAME}.local ${PUBLIC_IP}|awk '{print $2}')
		killall -9 	$_PROCES

}

add_service(){

	local _TXT

	_TXT=$(echo "$4"|tr "&" " ")

	avahi-publish-service -H ${NODENAME}.${CLOUD_NAME}.local $1 $2 $3 $_TXT &

	save_service ${NODENAME}.${CLOUD_NAME}.local ${PUBLIC_IP} $1 $2 $3 $_TXT 
}

rem_service(){
	
	local _PROCES
	local i

	_PROCES=$(ps fuax |grep avahi-publish-service|grep -v grep|grep $1|awk '{print $2}')

	for i in $_PROCES;
	do 
		kill -9 $i
	done
	if [ $(ps fuax |grep avahi-publish-service|grep -v grep| wc -l) -lt 1 ]
	then
		rem_host
	fi

}


# Find 
find_(){

	avahi-browse -aktrp|grep -e "=;$DEVICE_NAME;IPv4;.*;$1;.*;$2"|awk -F ";" '{print $7"("$5")-> "$8}'

}

publish_service() {

	local _DESCRIBE
	local _TYPE
	local _PORT
	local _TXT

	if [ $# -lt 3 ]
	then
		avahi-ps-help
	fi

	_DESCRIBE=$1
	_TYPE="_$2._tcp"
	_PORT=$3
	_TXT=${4:-""}
	add_host 
	add_service $_DESCRIBE $_TYPE $_PORT $_TXT
}

unpublish_service(){
	local _TYPE
	if [ $# -lt 1 ]
	then
		avahi-ps-help
	fi

	rem_service $1 
}
search_service(){

	local _SERVICE
	local _HOST
	echo "in find_:$@"
	echo "$CLOUD_NAME"
	if [ -z $1 ]
	then 
		echo "All service"
		_SERVICE=".*"
	else
		_SERVICE="_$1._tcp"
	fi
	if [ -z $2 ]
	then
		echo "All hosts"
		_HOST=".*\.$CLOUD_NAME\.local"
	else
		_HOST="$2\.$CLOUD_NAME\.local"
	fi
	find_ "$_SERVICE" "$_HOST"

}
