#!/bin/bash
#
TIMEOUT=10

memory_add_host(){

	# Validate if exist address node.
	if [ $(avahi-resolve-address -n ${NODENAME}.${CLOUD_NAME}.local 2> /dev/null | grep "${PUBLIC_IP}" | wc -l) -lt 1 ]
	then 
		avahi-publish-address -R ${NODENAME}.${CLOUD_NAME}.local ${PUBLIC_IP} 2> /dev/null &
	fi

}

memory_rem_host(){
	
		local _PROCES

		_PROCES=$(ps fuax| grep "avahi-publish-address -R ${NODENAME}.${CLOUD_NAME}.local ${PUBLIC_IP}"|grep -v grep|awk '{print $2}')
		[ ! -z "$_PROCES" ] && kill -9 $_PROCES

}

memory_add_service(){

	local _TXT

	_TXT=$(echo "$4"|tr "&" " ")

	if [ $(ps fax| grep "avahi-publish-service -H ${NODENAME}.${CLOUD_NAME}.local"|grep "$2 $3"|grep -v grep|wc -l) -eq 0 ]
		then
		avahi-publish-service -H ${NODENAME}.${CLOUD_NAME}.local "$1" "$2" "$3" $_TXT 2> /dev/null &
	fi

	save_service ${NODENAME}.${CLOUD_NAME}.local ${PUBLIC_IP} "$1" "$2" "$3" "$_TXT"
}

memory_rem_service(){
	
	local _PROCES
	local i


	_PROCES=$(ps fuax |grep avahi-publish-service|grep -v grep|grep "$1 $2"|awk '{print $2}')

	for i in $_PROCES
	do 
		kill -9 $i
	done
	if [ $(ps fuax |grep avahi-publish-service|grep -v grep| wc -l) -lt 1 ]
	then
		memory_rem_host
	fi

}


# Find 
memory_find_(){

	timeout $TIMEOUT avahi-browse -aktrp|grep -e "=;$DEVICE_NAME;IPv4;.*;$1;.*;$2"|awk -F ";" '{print $5";"$4";"$7";"$8";"$9";"$10}'

}

memory_publish_service() {

	local _DESCRIBE
	local _TYPE
	local _PORT
	local _TXT

	if [ $# -lt 3 ]
	then
		avahi-ps-help
	fi

	_DESCRIBE="$1"
	_TYPE="_${2}._tcp"
	_PORT="$3"
	_TXT=${4:-""}
	memory_add_host 
	memory_add_service "$_DESCRIBE" "$_TYPE" "$_PORT" $_TXT
}

memory_unpublish_service(){
	local _TYPE
	local _PORT

	if [ $# -lt 2 ]
	then
		avahi-ps-help
	fi
	_TYPE="_$1._tcp"
	_PORT=$2
	memory_rem_service $_TYPE $_PORT 
}

memory_search_service(){

	local _SERVICE
	local _HOST
	if [ -z "$1" -o "$1" == "." ]
	then 
		_SERVICE=".*"
	else
		_SERVICE="_$1._tcp"
	fi
	if [ -z "$2" -o "$2" == "." ]
	then
		_HOST=".*\.$CLOUD_NAME\.local"
	else
		_HOST="$2\.$CLOUD_NAME\.local"
	fi
	memory_find_ "$_SERVICE" "$_HOST"

}
